name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose up -d bugzilla-db tl-mariadb
          docker-compose up -d bugzilla-svc tl-testlink

      - name: Run Tests
        run: |
          # You can add commands here to test the services
          docker-compose exec bugzilla-svc curl -I http://localhost
          docker-compose exec tl-testlink curl -I http://localhost:83
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          scp -i $SSH_PRIVATE_KEY docker-compose.yml $USER@$HOST:/path/to/your/app
          ssh -i $SSH_PRIVATE_KEY $USER@$HOST "cd /path/to/your/app && docker-compose pull && docker-compose up -d"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}
          draft: false
          prerelease: false
