name: CI/CD Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 'dev'

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        #java-version: '21'
        java-version: 21
        distribution: 'temurin'
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 970547377893.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t eleos-registry:eureka-service-v1 .

    - name: Tag Docker image
      run: docker tag eleos-registry:eureka-service-v1 970547377893.dkr.ecr.ap-south-1.amazonaws.com/eleos-registry:eureka-service-v1

    - name: Push Docker image to Amazon ECR
      run: docker push 970547377893.dkr.ecr.ap-south-1.amazonaws.com/eleos-registry:eureka-service-v1
